[package]
name = "ayaflow-common"
version = "0.1.1"
edition = "2021"
publish = false

[features]
default = []
user = ["serde", "dep:aya"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[lib]
path = "src/lib.rs"

[target.'cfg(target_os = "linux")'.dependencies]
aya = { version = "0.13", optional = true }
